// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektFinal.Models;

namespace ProjektFinal.Migrations
{
    [DbContext(typeof(FilmContext))]
    [Migration("20210919145651_Prva")]
    partial class Prva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjektFinal.Models.FilmDetail", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GodinaProdukcije")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ukupnazarada")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FilmId");

                    b.ToTable("FilmDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
